### PR TITLE
Add arm64 builds and bump build number to 6

### PR DESCRIPTION
**Pull request by johnwason**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
For the cross-compile, if you have an executable that is run at build time, you'll need to build for the native architecture first, and then use that executable. See e.g. https://github.com/conda-forge/gz-msgs-feedstock/blob/9d8c3b4047d2f5ee69f9364bedf1153db438ac25/recipe/build_cxx.sh#L8-L30

**Comment by johnwason** [comment]
The binary RobotRaconteurGen is in the `robotraconteur` package. I would need to pull in the native version of that package to use it rather than build it here. I will need to use the cross arch library to compile against.

**Comment by Tobias-Fischer** [comment]
Ah I see, it’s easy then, just add it to the build packages (in addition to host) for cross platform builds. In the companion package here, you need to have a way to specify that the executable in BUILD_PREFIX instead of PREFIX should be used

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by johnwason** [comment]
Thanks @Tobias-Fischer

**Pull request merged**
